### ISSUE TITLE
SMS 2FA

### ISSUE THREAD

**Issue by bjorntj** [ventz/openconnect-gui-menu-bar#10]
Hi.

Found your script and worked great but only when I have already used my 2FA. I.e. if I need to input the pin code received on SMS, I do not see anywhere to input this pin code. 
Tried to look at the script but unsure how this input is suppose to work. Does the script not support inputing pin code after "connected" to the the vpn or am I missing something?

**Comment by ventz** [comment]
@bjorntj There are two parts:

1.) This line needs to be `pin`:
https://github.com/ventz/openconnect-gui-menu-bar/blob/089909e9315f6f37e42e3cff99cc4724a40d5720/openconnect.sh#L48

2.) Here is where you would be prompted for it:
https://github.com/ventz/openconnect-gui-menu-bar/blob/089909e9315f6f37e42e3cff99cc4724a40d5720/openconnect.sh#L92

Effectively, anything outside of the keywords: `push`, `sms`, and `phone` will assume that you are inputing a pin/token (be it TOTP token, or any other specific one to your auth framework)

**Comment by bjorntj** [comment]
Yes, I figured it out that that variable should be anything but push, or sms or phone but the problem seems to be that I am being asked for a pin before the sms is sent. I.e. it does not log on using username and password before asking for the pin.

**Comment by ventz** [comment]
@bjorntj You are saying that you type in user+pass, send it, and then your VPN concentrator/IAM generates a SMS that you get with the 2FA? That is, you don't have the TOTP/code before you submit the user+pass to the VPN?

If so - that may be a challenge as effectively you need an interactive console to OpenConnect to complete the auth.

You may be able to modify this line:
https://github.com/ventz/openconnect-gui-menu-bar/blob/089909e9315f6f37e42e3cff99cc4724a40d5720/openconnect.sh#L109

And introduce oascript to open a terminal and then execute it -- so you will have the ability to add additional inputs after the connection is established.

**Comment by bjorntj** [comment]
Yes, I guess that is what I am saying. :)
And I thought this might be a challenge. It works if I use openconnect interactively and handle everything manually. Then openconnect asks for password and the the pin code. When I try to input the password by using the echo command first, then the input prompt for the pin code do not work.

But I might have found a kind of solution, not as fancy but seems to work.

by using the following: cat <(echo -e "${VPN_PASSWORD}") /dev/stdin | sudo openconnect ....
