### ISSUE TITLE
Documentation: openconnect.sh needs to be marked executable

### ISSUE THREAD

**Issue by chipgwyn** [ventz/openconnect-gui-menu-bar#3]
Most everything works great, however the openconnect.sh script needs to be marked executable.  That's not specifically in the docs, but a few people got hung up at that part.  Otherwise perfect!

**Comment by ventz** [comment]
@chipgwyn Interesting, it should have been chmod 755 in the github repository already. I'll double check, but I'll also add a note about that in the README.

**Comment by ventz** [comment]
@chipgwyn All set - commit 96b22aa3c857cefbd9734435b82cc48d74ed9d09
