### ISSUE TITLE
Unable to add keychain password manually

### ISSUE THREAD

**Issue by boillodmanuel** [ventz/openconnect-gui-menu-bar#7]
I tried to add password in keychain manually but got `security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.` when trying to retrieve it.
I guess it could be caused by "https://xxx" in VPN_HOST (even if it seems useless to add `https://`)

So I use command line to set password and it works like a charm:
```bash
security add-generic-password -s openconnect -a $VPN_HOST -w
```
I also updated the `GET_VPN_PASSWORD` like that:
```bash
GET_VPN_PASSWORD="security find-generic-password -s openconnect -a $VPN_HOST -w"
```

That's said, thank you a lot for your plugin! 👍

**Comment by ventz** [comment]
@boillodmanuel The "VPN_HOST" should be just the FQDN of your vpn.

The `security find-generic-password -wl` should definitely work. Double check how you created it.
(I don't believe you want -s or -a when you add it)

Glad you are finding this helpful. Personally, it was driving me nuts not having something like this built in from Apple or at least a good 3rd party GUI.
