### ISSUE TITLE
Openconnect 'Failed to obtain WebVPN cookie' over sms authentication

### ISSUE THREAD

**Issue by codtiger** [ventz/openconnect-gui-menu-bar#9]
I tried the script in MacOS Monterey, even though it requires tons of changes( e.g. ` security find-generic-password` should be changed to `security find-internet-password` as new keychain entries are saved under `Interned Passwords`).

But on top of this, openconnect still doesn't wait for you to receive the 2fa sms (in my case, from DUO) and throws a `Failed to obtain WebVPN cookie` error before shutting down.

Has anyone found a way to bypass this problem caused by openconnect? Interesting enough using `push` allows openconnect to way for your push authentication before connection.

**Comment by ventz** [comment]
@codtiger Ive been using this on Monterey for the last 7 months with Duo (with push) without any issues. 

What you are seeing sounds like a potential issues with openconnect itself. I would suggest reaching out to the community.  

As for the keychain, the generic password is actually perfectly fine here. Internet password just provide additional fields and are reserved for configs accessed by wifi, vpn, and websites, where a web browser is needed. It provides other fields which you don’t need. Generic password is the lowest form and simplest secure enclave storage. 

see: https://ss64.com/osx/security.html and https://developer.apple.com/documentation/security/ksecclassgenericpassword
